"""
Accident Report Generator
Generates a downloadable PDF accident report for insurance/police use.
Uses only reportlab (pure Python, no external dependencies beyond pip).
Falls back to plain text if reportlab is not installed.
"""

from datetime import datetime
import io


def generate_report_text(data: dict) -> str:
    """Generate plain text report as fallback."""
    now = datetime.now().strftime("%d %B %Y, %I:%M %p")
    lines = [
        "=" * 60,
        "        ROAD ACCIDENT REPORT",
        "        Generated by RoadSoS Emergency Assistant",
        "=" * 60,
        f"Report Generated : {now}",
        "",
        "--- INCIDENT DETAILS ---",
        f"Date & Time      : {data.get('incident_date', 'N/A')} {data.get('incident_time', '')}",
        f"Location         : {data.get('location', 'N/A')}",
        f"Type of Accident : {data.get('accident_type', 'N/A')}",
        f"Road Condition   : {data.get('road_condition', 'N/A')}",
        f"Weather          : {data.get('weather', 'N/A')}",
        "",
        "--- REPORTER DETAILS ---",
        f"Name             : {data.get('reporter_name', 'N/A')}",
        f"Phone            : {data.get('reporter_phone', 'N/A')}",
        f"Role             : {data.get('reporter_role', 'N/A')}",
        "",
        "--- VEHICLES INVOLVED ---",
        f"Number of Vehicles: {data.get('num_vehicles', 'N/A')}",
        f"Vehicle 1        : {data.get('vehicle1', 'N/A')}",
        f"Vehicle 2        : {data.get('vehicle2', 'N/A')}",
        "",
        "--- CASUALTIES ---",
        f"Injured Persons  : {data.get('num_injured', '0')}",
        f"Fatalities       : {data.get('num_fatalities', '0')}",
        f"Injury Details   : {data.get('injury_details', 'N/A')}",
        "",
        "--- EMERGENCY SERVICES ---",
        f"Ambulance Called : {data.get('ambulance_called', 'N/A')}",
        f"Police Called    : {data.get('police_called', 'N/A')}",
        f"Hospital         : {data.get('hospital_name', 'N/A')}",
        "",
        "--- DESCRIPTION ---",
        data.get('description', 'N/A'),
        "",
        "--- WITNESS DETAILS ---",
        f"Witness Name     : {data.get('witness_name', 'N/A')}",
        f"Witness Phone    : {data.get('witness_phone', 'N/A')}",
        "",
        "=" * 60,
        "DISCLAIMER: This report is generated for reference purposes.",
        "Please file an official FIR at the nearest police station.",
        "=" * 60,
    ]
    return "\n".join(lines)


def generate_report_pdf(data: dict) -> bytes | None:
    """
    Generate a PDF accident report.
    Returns PDF bytes or None if reportlab is not available.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        Table, TableStyle, HRFlowable)
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        return None

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    now = datetime.now().strftime("%d %B %Y, %I:%M %p")

    # Custom styles
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#b71c1c"),
        spaceAfter=4, alignment=TA_CENTER
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#555555"),
        spaceAfter=2, alignment=TA_CENTER
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Normal"],
        fontSize=11, textColor=colors.white,
        fontName="Helvetica-Bold", spaceAfter=4, spaceBefore=10
    )
    field_label = ParagraphStyle(
        "FieldLabel", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#555555"),
        fontName="Helvetica-Bold"
    )
    field_value = ParagraphStyle(
        "FieldValue", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#111111")
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#888888"),
        alignment=TA_CENTER, spaceAfter=2
    )

    def section_header(title):
        tbl = Table([[Paragraph(f"  {title}", section_style)]], colWidths=[17*cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#b71c1c")),
            ("ROUNDEDCORNERS", [4]),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        return tbl

    def field_row(label, value):
        return Table(
            [[Paragraph(label, field_label), Paragraph(str(value) if value else "—", field_value)]],
            colWidths=[5*cm, 12*cm]
        )

    story = []

    # Header
    story.append(Paragraph("🚨 ROAD ACCIDENT REPORT", title_style))
    story.append(Paragraph("Generated by RoadSoS Emergency Assistant", subtitle_style))
    story.append(Paragraph(f"Report Date: {now}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#e53935")))
    story.append(Spacer(1, 0.3*cm))

    # Incident Details
    story.append(section_header("📍 INCIDENT DETAILS"))
    story.append(Spacer(1, 0.2*cm))
    story.append(field_row("Date & Time", f"{data.get('incident_date','')} {data.get('incident_time','')}"))
    story.append(field_row("Location", data.get("location", "")))
    story.append(field_row("Type of Accident", data.get("accident_type", "")))
    story.append(field_row("Road Condition", data.get("road_condition", "")))
    story.append(field_row("Weather", data.get("weather", "")))
    story.append(Spacer(1, 0.3*cm))

    # Reporter Details
    story.append(section_header("👤 REPORTER DETAILS"))
    story.append(Spacer(1, 0.2*cm))
    story.append(field_row("Full Name", data.get("reporter_name", "")))
    story.append(field_row("Phone Number", data.get("reporter_phone", "")))
    story.append(field_row("Role at Scene", data.get("reporter_role", "")))
    story.append(Spacer(1, 0.3*cm))

    # Vehicles
    story.append(section_header("🚗 VEHICLES INVOLVED"))
    story.append(Spacer(1, 0.2*cm))
    story.append(field_row("Number of Vehicles", data.get("num_vehicles", "")))
    story.append(field_row("Vehicle 1", data.get("vehicle1", "")))
    story.append(field_row("Vehicle 2", data.get("vehicle2", "")))
    story.append(Spacer(1, 0.3*cm))

    # Casualties
    story.append(section_header("🏥 CASUALTIES"))
    story.append(Spacer(1, 0.2*cm))
    story.append(field_row("Persons Injured", data.get("num_injured", "0")))
    story.append(field_row("Fatalities", data.get("num_fatalities", "0")))
    story.append(field_row("Injury Details", data.get("injury_details", "")))
    story.append(Spacer(1, 0.3*cm))

    # Emergency Services
    story.append(section_header("🚑 EMERGENCY SERVICES"))
    story.append(Spacer(1, 0.2*cm))
    story.append(field_row("Ambulance Called", data.get("ambulance_called", "")))
    story.append(field_row("Police Called", data.get("police_called", "")))
    story.append(field_row("Hospital Name", data.get("hospital_name", "")))
    story.append(Spacer(1, 0.3*cm))

    # Description
    story.append(section_header("📝 INCIDENT DESCRIPTION"))
    story.append(Spacer(1, 0.2*cm))
    desc_style = ParagraphStyle(
        "Desc", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#111111"),
        leading=16, spaceAfter=6
    )
    story.append(Paragraph(data.get("description", "No description provided."), desc_style))
    story.append(Spacer(1, 0.3*cm))

    # Witness
    story.append(section_header("👁️ WITNESS DETAILS"))
    story.append(Spacer(1, 0.2*cm))
    story.append(field_row("Witness Name", data.get("witness_name", "")))
    story.append(field_row("Witness Phone", data.get("witness_phone", "")))
    story.append(Spacer(1, 0.5*cm))

    # Disclaimer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        "⚠️ DISCLAIMER: This report is generated for reference purposes only. "
        "Please file an official FIR at the nearest police station and submit "
        "this report to your insurance provider.",
        disclaimer_style
    ))
    story.append(Paragraph(
        "RoadSoS Emergency Assistant · IIT Madras Road Safety Hackathon 2026",
        disclaimer_style
    ))

    doc.build(story)
    return buffer.getvalue()
